modLoader="javafml"
loaderVersion="[44,)"
license="MIT"

[[mods]]
    modId="improved_animations"
    version = "${version}"
    displayName="Improved Animations"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    logoFile="banner.png"
    credits="James Pelter (Trainguy), fmbellomy, MincraftEinstein"
    authors="James Pelter (Trainguy), Qboi123, adamdawoud , MincraftEinstein"
    description='''
Minecraft Animations Mod
'''

[modproperties.improved_animations]
    catalogueImageIcon="pack.png"

[[dependencies.improved_animations]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.improved_animations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
